[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

[profile.release-with-debug]
inherits = "release"
debug = true

[dependencies]
rayon = "1.5.0"

[dev-dependencies]
divan = "0.1.3" 

[[bench]]
name = "day05"
harness = false
